name: Deploy to second dev

on: workflow_dispatch

jobs:
  second_dev_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/initialize
        with:
          aws_access_key: ${{ secrets.MIRA_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.MIRA_AWS_SECRET_ACCESS_KEY }}

      - name: Deploy static site to S3 bucket
        env:
          BUCKET_NAME: "miraly-dev-second-website"
        run: aws s3 sync ./out/ s3://${{ env.BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DEV_SECOND_CLOUD_FRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
