# ===== ci(test) ======
name: ğŸ§ª Unit & E2E Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  e2e:
    # Sped up greatly via sharding across cores
    runs-on: ubuntu-latest # https://github.com/mira-amm/mira-amm-web/settings/actions/runners
    # runs-on: ubuntu-latest # Uncomment in case of self-hosted runner downtime. Slower test runs due to only 2 cores.
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: ğŸ› Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags to ensure the 'main' branch is available

      - name: ğŸŒ³ Fetch main branch # Will be used for test splitting later
        run: git fetch origin main # Explicitly fetch the 'main' branch to ensure it's available

      - name: ğŸŸ¨ Install pnpm
        uses: pnpm/action-setup@v4

      - name: ğŸŸ© Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: ğŸ“¦ Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: ğŸ— Build
        env:
          SENTIO_API_KEY: ${{ secrets.SENTIO_API_KEY }}
          NEXT_PUBLIC_ENABLE_REBRAND_UI: true
          FUEL_WALLET_PRIVATE_KEY: ${{ secrets.FUEL_WALLET_PRIVATE_KEY }}
        run: pnpm nx run-many -t build -p api ts-sdk design admin microgame web --verbose

      - name: ğŸ§© Run Unit test
        env:
          SENTIO_API_KEY: ${{ secrets.SENTIO_API_KEY }}
          NEXT_PUBLIC_ENABLE_REBRAND_UI: true
          FUEL_WALLET_PRIVATE_KEY: ${{ secrets.FUEL_WALLET_PRIVATE_KEY }}
        run: pnpm nx run-many -t test -p api web

      - name: ğŸ§ Run End-to-End tests
        env:
          SENTIO_API_KEY: ${{ secrets.SENTIO_API_KEY }}
          NEXT_PUBLIC_ENABLE_REBRAND_UI: true
          FUEL_WALLET_PRIVATE_KEY: ${{ secrets.FUEL_WALLET_PRIVATE_KEY }}
        run: xvfb-run pnpm nx run-many -t e2e -p api web-e2e --verbose

      - name: ğŸ“¸ Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: |
            apps/web-e2e/test-results/
            apps/web-e2e/playwright-report/
            apps/web-e2e/target/site/serenity/
          retention-days: 30
